### ISSUE TITLE
Cdegroot's Air Traffic Control Story

### ISSUE THREAD

**Issue by Jesse-Millwood** [emacs-love/tales#1]
cdegroot posted a story on reddit about how emacs was used in a subsystem of Germany's air traffic control at one point: https://www.reddit.com/r/emacs/comments/lly7po/do_you_use_emacs_lisp_as_a_general_purpose/gnvzisy/?context=3

**Comment by guilhermecomum** [comment]
Hey @Jesse-Millwood sorry the delay!
I have invited cdegroot to post the history or the permission to post, and he respond ask for a time to thinking about it. So let's wait!
Btw thank you so much to open the issue with the link? Do you have any stories to share?

Cheers!

**Comment by Jesse-Millwood** [comment]
Oh awesome! 
No, I personally don't have any emacs stories. Maybe someday!
